"""bound what one evaluation may spend at a model provider, and record what it spent

Before this revision nothing in the schema said how many model requests an evaluation was
allowed to make. Execution was bounded per mission by turns, tool calls and a deadline, and a
throttled provider was retried inside that deadline, so a suite could make several times as many
provider requests as it had missions with nothing recording that it had.

Three things land here.

`benchmark_evaluation_launch` gains the execution budget it was admitted with: the whole
launch's request ceiling, how much of it one mission may take, and the capacity policy version
those were computed under. All three are frozen by the existing guard trigger, exactly like
every other identity the merchant was shown, so widening the policy afterwards cannot rewrite
what a historical launch ran under.

Existing launches are left null rather than backfilled. They ran under no execution budget, and
inventing one for them would tell a reader they were bounded by something that did not exist.
The rule that a model buyer must have one is therefore an insert rule on the guard rather than a
check constraint: every launch admitted from here carries a budget, and every launch admitted
before this keeps the truth about itself.

`provider_capacity_policy` is one operator statement per provider: whether AgentRank may call it,
how many evaluations may run against it at once, how large an allowance an evaluation is admitted
with, and an optional deployment ceiling over a rolling window. No vendor quota is encoded. A
deployment that writes no row runs under a conservative default that lives in application code
and is reported as unconfigured.

`provider_execution_permit` is what was actually reserved: one row per mission, written and
committed before the process that makes the calls exists. It is keyed on the benchmark run rather
than on the merchant launch, because a run an operator starts to execute one sample of a
controlled experiment spends exactly the same provider quota as one a merchant asked for, and an
accounting that only knew about launches would have left that path charged to nothing.
`charged_requests` is generated by the database from the state and the two counts, so "what has
this run spent" has one implementation and no application copy that could drift from it. A permit
may leave RESERVED once and never return, and one that was assumed spent can never be reconciled
down to a smaller number, because doing so would restore allowance for a request that may already
have been paid for.

Revision ID: c1d4f8a2b6e3
Revises: c8d2e4f6a1b3
Created: 2026-08-26 09:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c1d4f8a2b6e3"
down_revision: str | None = "c8d2e4f6a1b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

LAUNCH = "benchmark_evaluation_launch"
POLICY = "provider_capacity_policy"
PERMIT = "provider_execution_permit"

KEY_PATTERN = r"^[a-z0-9]+(-[a-z0-9]+)*$"

CHARGE_EXPRESSION = (
    "CASE state"
    " WHEN 'RECONCILED'::text THEN consumed_requests"
    " WHEN 'RELEASED'::text THEN 0"
    " ELSE granted_requests"
    " END"
)

# The launch guard, replaced rather than amended, because a trigger function is replaced whole.
# Two things change: the three budget columns join the frozen identity, and an inserted model
# buyer launch must carry a budget. Everything else is exactly the previous revision's text.
GUARD = """
CREATE OR REPLACE FUNCTION benchmark_evaluation_launch_guard() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.id IS DISTINCT FROM OLD.id
            OR NEW.merchant_id IS DISTINCT FROM OLD.merchant_id
            OR NEW.request_key IS DISTINCT FROM OLD.request_key
            OR NEW.purpose IS DISTINCT FROM OLD.purpose
            OR NEW.representation_id IS DISTINCT FROM OLD.representation_id
            OR NEW.compiler_run_id IS DISTINCT FROM OLD.compiler_run_id
            OR NEW.source_snapshot_id IS DISTINCT FROM OLD.source_snapshot_id
            OR NEW.suite_id IS DISTINCT FROM OLD.suite_id
            OR NEW.environment_id IS DISTINCT FROM OLD.environment_id
            OR NEW.buyer_profile IS DISTINCT FROM OLD.buyer_profile
            OR NEW.buyer_configuration IS DISTINCT FROM OLD.buyer_configuration
            OR NEW.buyer_configuration_digest IS DISTINCT FROM OLD.buyer_configuration_digest
            OR NEW.executor_kind IS DISTINCT FROM OLD.executor_kind
            OR NEW.execution_budget_version IS DISTINCT FROM OLD.execution_budget_version
            OR NEW.max_provider_requests IS DISTINCT FROM OLD.max_provider_requests
            OR NEW.max_requests_per_mission IS DISTINCT FROM OLD.max_requests_per_mission
            OR NEW.baseline_run_id IS DISTINCT FROM OLD.baseline_run_id
            OR NEW.requested_at IS DISTINCT FROM OLD.requested_at
        THEN
            RAISE EXCEPTION 'benchmark evaluation launch identity is frozen at admission';
        END IF;

        IF OLD.run_id IS NOT NULL AND NEW.run_id IS DISTINCT FROM OLD.run_id THEN
            RAISE EXCEPTION 'a benchmark evaluation launch cannot be moved to another run';
        END IF;

        IF (OLD.status, NEW.status) NOT IN (
            ('QUEUED', 'QUEUED'),
            ('QUEUED', 'EXECUTING'),
            ('QUEUED', 'FAILED'),
            ('EXECUTING', 'EXECUTING'),
            ('EXECUTING', 'COMPLETED'),
            ('EXECUTING', 'FAILED')
        ) THEN
            RAISE EXCEPTION 'benchmark evaluation launch status cannot go from % to %',
                OLD.status, NEW.status;
        END IF;
    ELSE
        IF NEW.status <> 'QUEUED' THEN
            RAISE EXCEPTION
                'a benchmark evaluation launch is admitted queued, never written settled';
        END IF;

        IF NEW.buyer_profile = 'AI_BUYER' AND NEW.max_provider_requests IS NULL THEN
            RAISE EXCEPTION
                'a model buyer evaluation launch is admitted with an execution budget';
        END IF;

        IF NEW.buyer_profile <> 'AI_BUYER' AND NEW.max_provider_requests IS NOT NULL THEN
            RAISE EXCEPTION
                'only a model buyer evaluation launch carries a provider execution budget';
        END IF;
    END IF;

    IF NEW.status = 'COMPLETED' AND (
        SELECT status FROM benchmark_run WHERE id = NEW.run_id
    ) IS DISTINCT FROM 'COMPLETED' THEN
        RAISE EXCEPTION 'a completed evaluation launch must name a completed benchmark run';
    END IF;

    IF NEW.status = 'FAILED' AND NEW.run_id IS NOT NULL AND (
        SELECT status FROM benchmark_run WHERE id = NEW.run_id
    ) IS DISTINCT FROM 'ABORTED' THEN
        RAISE EXCEPTION 'a failed evaluation launch that names a run must name an aborted one';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql
"""

PREVIOUS_GUARD = """
CREATE OR REPLACE FUNCTION benchmark_evaluation_launch_guard() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.id IS DISTINCT FROM OLD.id
            OR NEW.merchant_id IS DISTINCT FROM OLD.merchant_id
            OR NEW.request_key IS DISTINCT FROM OLD.request_key
            OR NEW.purpose IS DISTINCT FROM OLD.purpose
            OR NEW.representation_id IS DISTINCT FROM OLD.representation_id
            OR NEW.compiler_run_id IS DISTINCT FROM OLD.compiler_run_id
            OR NEW.source_snapshot_id IS DISTINCT FROM OLD.source_snapshot_id
            OR NEW.suite_id IS DISTINCT FROM OLD.suite_id
            OR NEW.environment_id IS DISTINCT FROM OLD.environment_id
            OR NEW.buyer_profile IS DISTINCT FROM OLD.buyer_profile
            OR NEW.buyer_configuration IS DISTINCT FROM OLD.buyer_configuration
            OR NEW.buyer_configuration_digest IS DISTINCT FROM OLD.buyer_configuration_digest
            OR NEW.executor_kind IS DISTINCT FROM OLD.executor_kind
            OR NEW.baseline_run_id IS DISTINCT FROM OLD.baseline_run_id
            OR NEW.requested_at IS DISTINCT FROM OLD.requested_at
        THEN
            RAISE EXCEPTION 'benchmark evaluation launch identity is frozen at admission';
        END IF;

        IF OLD.run_id IS NOT NULL AND NEW.run_id IS DISTINCT FROM OLD.run_id THEN
            RAISE EXCEPTION 'a benchmark evaluation launch cannot be moved to another run';
        END IF;

        IF (OLD.status, NEW.status) NOT IN (
            ('QUEUED', 'QUEUED'),
            ('QUEUED', 'EXECUTING'),
            ('QUEUED', 'FAILED'),
            ('EXECUTING', 'EXECUTING'),
            ('EXECUTING', 'COMPLETED'),
            ('EXECUTING', 'FAILED')
        ) THEN
            RAISE EXCEPTION 'benchmark evaluation launch status cannot go from % to %',
                OLD.status, NEW.status;
        END IF;
    ELSIF NEW.status <> 'QUEUED' THEN
        RAISE EXCEPTION 'a benchmark evaluation launch is admitted queued, never written settled';
    END IF;

    IF NEW.status = 'COMPLETED' AND (
        SELECT status FROM benchmark_run WHERE id = NEW.run_id
    ) IS DISTINCT FROM 'COMPLETED' THEN
        RAISE EXCEPTION 'a completed evaluation launch must name a completed benchmark run';
    END IF;

    IF NEW.status = 'FAILED' AND NEW.run_id IS NOT NULL AND (
        SELECT status FROM benchmark_run WHERE id = NEW.run_id
    ) IS DISTINCT FROM 'ABORTED' THEN
        RAISE EXCEPTION 'a failed evaluation launch that names a run must name an aborted one';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql
"""

PERMIT_GUARD = """
CREATE FUNCTION provider_execution_permit_guard() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.state <> 'RESERVED' THEN
            RAISE EXCEPTION 'a provider execution permit is written reserved, never settled';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.id IS DISTINCT FROM OLD.id
        OR NEW.merchant_id IS DISTINCT FROM OLD.merchant_id
        OR NEW.launch_id IS DISTINCT FROM OLD.launch_id
        OR NEW.run_id IS DISTINCT FROM OLD.run_id
        OR NEW.mission_key IS DISTINCT FROM OLD.mission_key
        OR NEW.attempt IS DISTINCT FROM OLD.attempt
        OR NEW.attempt_key IS DISTINCT FROM OLD.attempt_key
        OR NEW.provider IS DISTINCT FROM OLD.provider
        OR NEW.requested_model IS DISTINCT FROM OLD.requested_model
        OR NEW.policy_version IS DISTINCT FROM OLD.policy_version
        OR NEW.granted_requests IS DISTINCT FROM OLD.granted_requests
        OR NEW.opened_at IS DISTINCT FROM OLD.opened_at
    THEN
        RAISE EXCEPTION 'a provider execution permit reservation is frozen once written';
    END IF;

    IF OLD.state <> 'RESERVED' THEN
        RAISE EXCEPTION
            'provider execution permit % is already %, and a settled permit never reopens',
            OLD.id, OLD.state;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql
"""

PERMIT_DELETE_GUARD = """
CREATE FUNCTION provider_execution_permit_delete_guard() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'a provider execution permit is spending evidence and cannot be deleted';
END;
$$ LANGUAGE plpgsql
"""


def upgrade() -> None:
    op.add_column(LAUNCH, sa.Column("execution_budget_version", sa.Integer(), nullable=True))
    op.add_column(LAUNCH, sa.Column("max_provider_requests", sa.Integer(), nullable=True))
    op.add_column(LAUNCH, sa.Column("max_requests_per_mission", sa.Integer(), nullable=True))
    op.create_check_constraint(
        "budget_shape",
        LAUNCH,
        "(max_provider_requests IS NULL) = (max_requests_per_mission IS NULL)"
        " AND (max_provider_requests IS NULL) = (execution_budget_version IS NULL)",
    )
    op.create_check_constraint(
        "budget_total_positive",
        LAUNCH,
        "max_provider_requests IS NULL OR max_provider_requests >= 1",
    )
    op.create_check_constraint(
        "budget_mission_positive",
        LAUNCH,
        "max_requests_per_mission IS NULL OR max_requests_per_mission >= 1",
    )
    op.create_check_constraint(
        "budget_mission_within_total",
        LAUNCH,
        "max_requests_per_mission IS NULL OR max_requests_per_mission <= max_provider_requests",
    )
    op.create_check_constraint(
        "budget_version_positive",
        LAUNCH,
        "execution_budget_version IS NULL OR execution_budget_version >= 1",
    )
    # What the permit's composite foreign key points at, so a permit can never name one
    # merchant's launch while claiming to belong to another's.
    op.create_unique_constraint(
        "uq_benchmark_evaluation_launch_tenant", LAUNCH, ["id", "merchant_id"]
    )
    op.execute(GUARD)

    op.create_table(
        POLICY,
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("max_concurrent_launches", sa.Integer(), nullable=False),
        sa.Column("mission_request_multiplier", sa.Integer(), nullable=False),
        sa.Column("launch_retry_allowance_percent", sa.Integer(), nullable=False),
        sa.Column("max_requests_per_window", sa.Integer(), nullable=True),
        sa.Column("window_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_capacity_policy"),
        sa.UniqueConstraint("provider", name="uq_provider_capacity_policy_provider"),
        sa.CheckConstraint(f"provider ~ '{KEY_PATTERN}'", name="provider_format"),
        sa.CheckConstraint("version >= 1", name="version_positive"),
        sa.CheckConstraint("max_concurrent_launches >= 1", name="concurrency_positive"),
        sa.CheckConstraint(
            "mission_request_multiplier >= 1",
            name="mission_multiplier_positive",
        ),
        sa.CheckConstraint(
            "launch_retry_allowance_percent >= 0 AND launch_retry_allowance_percent <= 1000",
            name="retry_allowance_bounded",
        ),
        sa.CheckConstraint(
            "max_requests_per_window IS NULL OR max_requests_per_window >= 1",
            name="window_cap_positive",
        ),
        sa.CheckConstraint("window_seconds >= 60", name="window_is_meaningful"),
    )

    op.create_table(
        PERMIT,
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("launch_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("mission_key", sa.String(length=64), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("attempt_key", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("requested_model", sa.String(length=128), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("granted_requests", sa.Integer(), nullable=False),
        sa.Column("consumed_requests", sa.Integer(), nullable=True),
        sa.Column(
            "charged_requests",
            sa.Integer(),
            sa.Computed(CHARGE_EXPRESSION, persisted=True),
            nullable=False,
        ),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_provider_execution_permit"),
        sa.UniqueConstraint("run_id", "attempt_key", name="uq_provider_execution_permit_attempt"),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchant.id"],
            name="fk_provider_execution_permit_merchant_id_merchant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["launch_id", "merchant_id"],
            ["benchmark_evaluation_launch.id", "benchmark_evaluation_launch.merchant_id"],
            name="fk_provider_execution_permit_launch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "merchant_id"],
            ["benchmark_run.id", "benchmark_run.merchant_id"],
            name="fk_provider_execution_permit_run",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "state IN ('RESERVED', 'RECONCILED', 'ASSUMED_SPENT', 'RELEASED')",
            name="state_known",
        ),
        sa.CheckConstraint(f"provider ~ '{KEY_PATTERN}'", name="provider_format"),
        sa.CheckConstraint("granted_requests >= 1", name="grant_positive"),
        sa.CheckConstraint("attempt >= 1", name="attempt_positive"),
        sa.CheckConstraint("policy_version >= 1", name="policy_version_positive"),
        sa.CheckConstraint(
            "(state = 'RECONCILED') = (consumed_requests IS NOT NULL)",
            name="consumption_shape",
        ),
        sa.CheckConstraint(
            "consumed_requests IS NULL"
            " OR (consumed_requests >= 0 AND consumed_requests <= granted_requests)",
            name="consumption_bounded",
        ),
        sa.CheckConstraint(
            "(state <> 'RESERVED') = (closed_at IS NOT NULL)",
            name="closed_shape",
        ),
        sa.CheckConstraint(
            "closed_at IS NULL OR closed_at >= opened_at",
            name="close_after_open",
        ),
    )
    op.create_index(
        "ix_provider_execution_permit_provider_opened_at", PERMIT, ["provider", "opened_at"]
    )
    op.create_index("ix_provider_execution_permit_run_id", PERMIT, ["run_id"])
    op.create_index(
        "ix_provider_execution_permit_launch_id",
        PERMIT,
        ["launch_id"],
        postgresql_where=sa.text("launch_id IS NOT NULL"),
    )
    op.create_index(
        "ix_provider_execution_permit_merchant_id_opened_at", PERMIT, ["merchant_id", "opened_at"]
    )
    op.create_index(
        "ix_provider_execution_permit_run_id_merchant_id", PERMIT, ["run_id", "merchant_id"]
    )

    op.execute(PERMIT_GUARD)
    op.execute(PERMIT_DELETE_GUARD)
    op.execute(
        "CREATE TRIGGER provider_execution_permit_guard"
        " BEFORE INSERT OR UPDATE ON provider_execution_permit"
        " FOR EACH ROW EXECUTE FUNCTION provider_execution_permit_guard()"
    )
    op.execute(
        "CREATE TRIGGER provider_execution_permit_delete_guard"
        " BEFORE DELETE ON provider_execution_permit"
        " FOR EACH ROW EXECUTE FUNCTION provider_execution_permit_delete_guard()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER provider_execution_permit_delete_guard ON provider_execution_permit")
    op.execute("DROP TRIGGER provider_execution_permit_guard ON provider_execution_permit")
    op.execute("DROP FUNCTION provider_execution_permit_delete_guard()")
    op.execute("DROP FUNCTION provider_execution_permit_guard()")
    op.drop_index("ix_provider_execution_permit_run_id_merchant_id", PERMIT)
    op.drop_index("ix_provider_execution_permit_merchant_id_opened_at", PERMIT)
    op.drop_index("ix_provider_execution_permit_launch_id", PERMIT)
    op.drop_index("ix_provider_execution_permit_run_id", PERMIT)
    op.drop_index("ix_provider_execution_permit_provider_opened_at", PERMIT)
    op.drop_table(PERMIT)
    op.drop_table(POLICY)

    op.execute(PREVIOUS_GUARD)
    op.drop_constraint("uq_benchmark_evaluation_launch_tenant", LAUNCH, type_="unique")
    op.drop_constraint("budget_version_positive", LAUNCH, type_="check")
    op.drop_constraint("budget_mission_within_total", LAUNCH, type_="check")
    op.drop_constraint("budget_mission_positive", LAUNCH, type_="check")
    op.drop_constraint("budget_total_positive", LAUNCH, type_="check")
    op.drop_constraint("budget_shape", LAUNCH, type_="check")
    op.drop_column(LAUNCH, "max_requests_per_mission")
    op.drop_column(LAUNCH, "max_provider_requests")
    op.drop_column(LAUNCH, "execution_budget_version")
